services:
  - type: web
    name: cyber-inventory-backend
    env: node
    buildCommand: npm install
    startCommand: node backend/server.js
    envVars:
      - key: JWT_SECRET
        value: supersecretcyberkey2024
      - key: PORT
        value: 3000